# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75fda5b3316fb72669c81d904bfac825626a9ef7c48ec10b023d10de164248183f00663aa5481bd4474d5ea4f79e32dab6c817daf5109b46a77255f3b93b5edb

test:
  secret_key_base: b5f156694d3a5c3916cb719bc7e57953a7ee741fdcdf7236e5c460a3320a828112d24c9600b386e0316c56e62e274470720f8ccd65cef625a3a10741eae9fec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
